//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceLoginGTH
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserInfo", Namespace="http://ArandaCMDBService.org/")]
    public partial class UserInfo : object
    {
        
        private string LanguageField;
        
        private string EmailField;
        
        private string LoginField;
        
        private string PasswordField;
        
        private string NameField;
        
        private int IdField;
        
        private int ProfileIdField;
        
        private int RoleIdField;
        
        private int ActiveUserField;
        
        private string EmailAssistantField;
        
        private System.Nullable<System.DateTime> PasswordChangeDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Language
        {
            get
            {
                return this.LanguageField;
            }
            set
            {
                this.LanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int ProfileId
        {
            get
            {
                return this.ProfileIdField;
            }
            set
            {
                this.ProfileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int RoleId
        {
            get
            {
                return this.RoleIdField;
            }
            set
            {
                this.RoleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int ActiveUser
        {
            get
            {
                return this.ActiveUserField;
            }
            set
            {
                this.ActiveUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string EmailAssistant
        {
            get
            {
                return this.EmailAssistantField;
            }
            set
            {
                this.EmailAssistantField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> PasswordChangeDate
        {
            get
            {
                return this.PasswordChangeDateField;
            }
            set
            {
                this.PasswordChangeDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://ArandaCMDBService.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LdapInfo", Namespace="http://ArandaCMDBService.org/")]
    public partial class LdapInfo : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string PathField;
        
        private string UserStringField;
        
        private int SecurityField;
        
        private int ConnectionTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserString
        {
            get
            {
                return this.UserStringField;
            }
            set
            {
                this.UserStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Security
        {
            get
            {
                return this.SecurityField;
            }
            set
            {
                this.SecurityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int ConnectionType
        {
            get
            {
                return this.ConnectionTypeField;
            }
            set
            {
                this.ConnectionTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ArandaCMDBService.org/", ConfigurationName="ServiceLoginGTH.AuthenticationSoap")]
    public interface AuthenticationSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetUserbyId", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.GetUserbyIdResponse> GetUserbyIdAsync(ServiceLoginGTH.GetUserbyIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetUserbyName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.GetUserbyNameResponse> GetUserbyNameAsync(ServiceLoginGTH.GetUserbyNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserLanguage", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserLanguageResponse> UpdateUserLanguageAsync(ServiceLoginGTH.UpdateUserLanguageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserPasswordResponse> UpdateUserPasswordAsync(ServiceLoginGTH.UpdateUserPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserEmail", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserEmailResponse> UpdateUserEmailAsync(ServiceLoginGTH.UpdateUserEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUserName", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserNameResponse> UpdateUserNameAsync(ServiceLoginGTH.UpdateUserNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UpdateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserResponse> UpdateUserAsync(ServiceLoginGTH.UpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/ActivateUser", ReplyAction="*")]
        System.Threading.Tasks.Task ActivateUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/UnactivateUser", ReplyAction="*")]
        System.Threading.Tasks.Task UnactivateUserAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserAD", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserADResponse> AutenticateUserADAsync(ServiceLoginGTH.AutenticateUserADRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/GetDomains", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.GetDomainsResponse> GetDomainsAsync(ServiceLoginGTH.GetDomainsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserDB", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserDBResponse> AutenticateUserDBAsync(ServiceLoginGTH.AutenticateUserDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUserDBEncrip", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserDBEncripResponse> AutenticateUserDBEncripAsync(ServiceLoginGTH.AutenticateUserDBEncripRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/ListServers", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.ListServersResponse> ListServersAsync(ServiceLoginGTH.ListServersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/AutenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserResponse> AutenticateUserAsync(ServiceLoginGTH.AutenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ArandaCMDBService.org/RememberPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceLoginGTH.RememberPasswordResponse> RememberPasswordAsync(ServiceLoginGTH.RememberPasswordRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyId", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.GetUserbyIdRequestBody Body;
        
        public GetUserbyIdRequest()
        {
        }
        
        public GetUserbyIdRequest(ServiceLoginGTH.GetUserbyIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetUserbyIdRequestBody()
        {
        }
        
        public GetUserbyIdRequestBody(int userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyIdResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.GetUserbyIdResponseBody Body;
        
        public GetUserbyIdResponse()
        {
        }
        
        public GetUserbyIdResponse(ServiceLoginGTH.GetUserbyIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.UserInfo GetUserbyIdResult;
        
        public GetUserbyIdResponseBody()
        {
        }
        
        public GetUserbyIdResponseBody(ServiceLoginGTH.UserInfo GetUserbyIdResult)
        {
            this.GetUserbyIdResult = GetUserbyIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyName", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.GetUserbyNameRequestBody Body;
        
        public GetUserbyNameRequest()
        {
        }
        
        public GetUserbyNameRequest(ServiceLoginGTH.GetUserbyNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public GetUserbyNameRequestBody()
        {
        }
        
        public GetUserbyNameRequestBody(string userName)
        {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserbyNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserbyNameResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.GetUserbyNameResponseBody Body;
        
        public GetUserbyNameResponse()
        {
        }
        
        public GetUserbyNameResponse(ServiceLoginGTH.GetUserbyNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetUserbyNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.UserInfo GetUserbyNameResult;
        
        public GetUserbyNameResponseBody()
        {
        }
        
        public GetUserbyNameResponseBody(ServiceLoginGTH.UserInfo GetUserbyNameResult)
        {
            this.GetUserbyNameResult = GetUserbyNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserLanguageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserLanguage", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserLanguageRequestBody Body;
        
        public UpdateUserLanguageRequest()
        {
        }
        
        public UpdateUserLanguageRequest(ServiceLoginGTH.UpdateUserLanguageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserLanguageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string language;
        
        public UpdateUserLanguageRequestBody()
        {
        }
        
        public UpdateUserLanguageRequestBody(int userId, string language)
        {
            this.userId = userId;
            this.language = language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserLanguageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserLanguageResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserLanguageResponseBody Body;
        
        public UpdateUserLanguageResponse()
        {
        }
        
        public UpdateUserLanguageResponse(ServiceLoginGTH.UpdateUserLanguageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserLanguageResponseBody
    {
        
        public UpdateUserLanguageResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPassword", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserPasswordRequestBody Body;
        
        public UpdateUserPasswordRequest()
        {
        }
        
        public UpdateUserPasswordRequest(ServiceLoginGTH.UpdateUserPasswordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserPasswordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string oldPassword;
        
        public UpdateUserPasswordRequestBody()
        {
        }
        
        public UpdateUserPasswordRequestBody(int userId, string password, string oldPassword)
        {
            this.userId = userId;
            this.password = password;
            this.oldPassword = oldPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPasswordResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserPasswordResponseBody Body;
        
        public UpdateUserPasswordResponse()
        {
        }
        
        public UpdateUserPasswordResponse(ServiceLoginGTH.UpdateUserPasswordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserPasswordResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserPasswordResult;
        
        public UpdateUserPasswordResponseBody()
        {
        }
        
        public UpdateUserPasswordResponseBody(bool UpdateUserPasswordResult)
        {
            this.UpdateUserPasswordResult = UpdateUserPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserEmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserEmail", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserEmailRequestBody Body;
        
        public UpdateUserEmailRequest()
        {
        }
        
        public UpdateUserEmailRequest(ServiceLoginGTH.UpdateUserEmailRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserEmailRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public UpdateUserEmailRequestBody()
        {
        }
        
        public UpdateUserEmailRequestBody(int userId, string email)
        {
            this.userId = userId;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserEmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserEmailResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserEmailResponseBody Body;
        
        public UpdateUserEmailResponse()
        {
        }
        
        public UpdateUserEmailResponse(ServiceLoginGTH.UpdateUserEmailResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserEmailResponseBody
    {
        
        public UpdateUserEmailResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserName", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserNameRequestBody Body;
        
        public UpdateUserNameRequest()
        {
        }
        
        public UpdateUserNameRequest(ServiceLoginGTH.UpdateUserNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public UpdateUserNameRequestBody()
        {
        }
        
        public UpdateUserNameRequestBody(int userId, string name)
        {
            this.userId = userId;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserNameResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserNameResponseBody Body;
        
        public UpdateUserNameResponse()
        {
        }
        
        public UpdateUserNameResponse(ServiceLoginGTH.UpdateUserNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserNameResponseBody
    {
        
        public UpdateUserNameResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserRequestBody Body;
        
        public UpdateUserRequest()
        {
        }
        
        public UpdateUserRequest(ServiceLoginGTH.UpdateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class UpdateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.UserInfo item;
        
        public UpdateUserRequestBody()
        {
        }
        
        public UpdateUserRequestBody(ServiceLoginGTH.UserInfo item)
        {
            this.item = item;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.UpdateUserResponseBody Body;
        
        public UpdateUserResponse()
        {
        }
        
        public UpdateUserResponse(ServiceLoginGTH.UpdateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateUserResponseBody
    {
        
        public UpdateUserResponseBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserADRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserAD", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserADRequestBody Body;
        
        public AutenticateUserADRequest()
        {
        }
        
        public AutenticateUserADRequest(ServiceLoginGTH.AutenticateUserADRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserADRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string domain;
        
        public AutenticateUserADRequestBody()
        {
        }
        
        public AutenticateUserADRequestBody(string userName, string password, string domain)
        {
            this.userName = userName;
            this.password = password;
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserADResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserADResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserADResponseBody Body;
        
        public AutenticateUserADResponse()
        {
        }
        
        public AutenticateUserADResponse(ServiceLoginGTH.AutenticateUserADResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserADResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.UserInfo AutenticateUserADResult;
        
        public AutenticateUserADResponseBody()
        {
        }
        
        public AutenticateUserADResponseBody(ServiceLoginGTH.UserInfo AutenticateUserADResult)
        {
            this.AutenticateUserADResult = AutenticateUserADResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomains", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.GetDomainsRequestBody Body;
        
        public GetDomainsRequest()
        {
        }
        
        public GetDomainsRequest(ServiceLoginGTH.GetDomainsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDomainsRequestBody
    {
        
        public GetDomainsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomainsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomainsResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.GetDomainsResponseBody Body;
        
        public GetDomainsResponse()
        {
        }
        
        public GetDomainsResponse(ServiceLoginGTH.GetDomainsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class GetDomainsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.ArrayOfString GetDomainsResult;
        
        public GetDomainsResponseBody()
        {
        }
        
        public GetDomainsResponseBody(ServiceLoginGTH.ArrayOfString GetDomainsResult)
        {
            this.GetDomainsResult = GetDomainsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDB", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserDBRequestBody Body;
        
        public AutenticateUserDBRequest()
        {
        }
        
        public AutenticateUserDBRequest(ServiceLoginGTH.AutenticateUserDBRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AutenticateUserDBRequestBody()
        {
        }
        
        public AutenticateUserDBRequestBody(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDBResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserDBResponseBody Body;
        
        public AutenticateUserDBResponse()
        {
        }
        
        public AutenticateUserDBResponse(ServiceLoginGTH.AutenticateUserDBResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.UserInfo AutenticateUserDBResult;
        
        public AutenticateUserDBResponseBody()
        {
        }
        
        public AutenticateUserDBResponseBody(ServiceLoginGTH.UserInfo AutenticateUserDBResult)
        {
            this.AutenticateUserDBResult = AutenticateUserDBResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBEncripRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDBEncrip", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserDBEncripRequestBody Body;
        
        public AutenticateUserDBEncripRequest()
        {
        }
        
        public AutenticateUserDBEncripRequest(ServiceLoginGTH.AutenticateUserDBEncripRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBEncripRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AutenticateUserDBEncripRequestBody()
        {
        }
        
        public AutenticateUserDBEncripRequestBody(string userName, string password)
        {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserDBEncripResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserDBEncripResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserDBEncripResponseBody Body;
        
        public AutenticateUserDBEncripResponse()
        {
        }
        
        public AutenticateUserDBEncripResponse(ServiceLoginGTH.AutenticateUserDBEncripResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserDBEncripResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.UserInfo AutenticateUserDBEncripResult;
        
        public AutenticateUserDBEncripResponseBody()
        {
        }
        
        public AutenticateUserDBEncripResponseBody(ServiceLoginGTH.UserInfo AutenticateUserDBEncripResult)
        {
            this.AutenticateUserDBEncripResult = AutenticateUserDBEncripResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListServersRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListServers", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.ListServersRequestBody Body;
        
        public ListServersRequest()
        {
        }
        
        public ListServersRequest(ServiceLoginGTH.ListServersRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListServersRequestBody
    {
        
        public ListServersRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListServersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListServersResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.ListServersResponseBody Body;
        
        public ListServersResponse()
        {
        }
        
        public ListServersResponse(ServiceLoginGTH.ListServersResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class ListServersResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.LdapInfo[] ListServersResult;
        
        public ListServersResponseBody()
        {
        }
        
        public ListServersResponseBody(ServiceLoginGTH.LdapInfo[] ListServersResult)
        {
            this.ListServersResult = ListServersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUser", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserRequestBody Body;
        
        public AutenticateUserRequest()
        {
        }
        
        public AutenticateUserRequest(ServiceLoginGTH.AutenticateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int serverId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        public AutenticateUserRequestBody()
        {
        }
        
        public AutenticateUserRequestBody(int serverId, string userName, string password)
        {
            this.serverId = serverId;
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AutenticateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AutenticateUserResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.AutenticateUserResponseBody Body;
        
        public AutenticateUserResponse()
        {
        }
        
        public AutenticateUserResponse(ServiceLoginGTH.AutenticateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class AutenticateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceLoginGTH.UserInfo AutenticateUserResult;
        
        public AutenticateUserResponseBody()
        {
        }
        
        public AutenticateUserResponseBody(ServiceLoginGTH.UserInfo AutenticateUserResult)
        {
            this.AutenticateUserResult = AutenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RememberPasswordRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RememberPassword", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.RememberPasswordRequestBody Body;
        
        public RememberPasswordRequest()
        {
        }
        
        public RememberPasswordRequest(ServiceLoginGTH.RememberPasswordRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class RememberPasswordRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        public RememberPasswordRequestBody()
        {
        }
        
        public RememberPasswordRequestBody(string userName)
        {
            this.userName = userName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RememberPasswordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RememberPasswordResponse", Namespace="http://ArandaCMDBService.org/", Order=0)]
        public ServiceLoginGTH.RememberPasswordResponseBody Body;
        
        public RememberPasswordResponse()
        {
        }
        
        public RememberPasswordResponse(ServiceLoginGTH.RememberPasswordResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://ArandaCMDBService.org/")]
    public partial class RememberPasswordResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RememberPasswordResult;
        
        public RememberPasswordResponseBody()
        {
        }
        
        public RememberPasswordResponseBody(bool RememberPasswordResult)
        {
            this.RememberPasswordResult = RememberPasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface AuthenticationSoapChannel : ServiceLoginGTH.AuthenticationSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class AuthenticationSoapClient : System.ServiceModel.ClientBase<ServiceLoginGTH.AuthenticationSoap>, ServiceLoginGTH.AuthenticationSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.GetUserbyIdResponse> ServiceLoginGTH.AuthenticationSoap.GetUserbyIdAsync(ServiceLoginGTH.GetUserbyIdRequest request)
        {
            return base.Channel.GetUserbyIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.GetUserbyIdResponse> GetUserbyIdAsync(int userId)
        {
            ServiceLoginGTH.GetUserbyIdRequest inValue = new ServiceLoginGTH.GetUserbyIdRequest();
            inValue.Body = new ServiceLoginGTH.GetUserbyIdRequestBody();
            inValue.Body.userId = userId;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).GetUserbyIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.GetUserbyNameResponse> ServiceLoginGTH.AuthenticationSoap.GetUserbyNameAsync(ServiceLoginGTH.GetUserbyNameRequest request)
        {
            return base.Channel.GetUserbyNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.GetUserbyNameResponse> GetUserbyNameAsync(string userName)
        {
            ServiceLoginGTH.GetUserbyNameRequest inValue = new ServiceLoginGTH.GetUserbyNameRequest();
            inValue.Body = new ServiceLoginGTH.GetUserbyNameRequestBody();
            inValue.Body.userName = userName;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).GetUserbyNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserLanguageResponse> ServiceLoginGTH.AuthenticationSoap.UpdateUserLanguageAsync(ServiceLoginGTH.UpdateUserLanguageRequest request)
        {
            return base.Channel.UpdateUserLanguageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserLanguageResponse> UpdateUserLanguageAsync(int userId, string language)
        {
            ServiceLoginGTH.UpdateUserLanguageRequest inValue = new ServiceLoginGTH.UpdateUserLanguageRequest();
            inValue.Body = new ServiceLoginGTH.UpdateUserLanguageRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.language = language;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).UpdateUserLanguageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserPasswordResponse> ServiceLoginGTH.AuthenticationSoap.UpdateUserPasswordAsync(ServiceLoginGTH.UpdateUserPasswordRequest request)
        {
            return base.Channel.UpdateUserPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserPasswordResponse> UpdateUserPasswordAsync(int userId, string password, string oldPassword)
        {
            ServiceLoginGTH.UpdateUserPasswordRequest inValue = new ServiceLoginGTH.UpdateUserPasswordRequest();
            inValue.Body = new ServiceLoginGTH.UpdateUserPasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.password = password;
            inValue.Body.oldPassword = oldPassword;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).UpdateUserPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserEmailResponse> ServiceLoginGTH.AuthenticationSoap.UpdateUserEmailAsync(ServiceLoginGTH.UpdateUserEmailRequest request)
        {
            return base.Channel.UpdateUserEmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserEmailResponse> UpdateUserEmailAsync(int userId, string email)
        {
            ServiceLoginGTH.UpdateUserEmailRequest inValue = new ServiceLoginGTH.UpdateUserEmailRequest();
            inValue.Body = new ServiceLoginGTH.UpdateUserEmailRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.email = email;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).UpdateUserEmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserNameResponse> ServiceLoginGTH.AuthenticationSoap.UpdateUserNameAsync(ServiceLoginGTH.UpdateUserNameRequest request)
        {
            return base.Channel.UpdateUserNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserNameResponse> UpdateUserNameAsync(int userId, string name)
        {
            ServiceLoginGTH.UpdateUserNameRequest inValue = new ServiceLoginGTH.UpdateUserNameRequest();
            inValue.Body = new ServiceLoginGTH.UpdateUserNameRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.name = name;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).UpdateUserNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserResponse> ServiceLoginGTH.AuthenticationSoap.UpdateUserAsync(ServiceLoginGTH.UpdateUserRequest request)
        {
            return base.Channel.UpdateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.UpdateUserResponse> UpdateUserAsync(ServiceLoginGTH.UserInfo item)
        {
            ServiceLoginGTH.UpdateUserRequest inValue = new ServiceLoginGTH.UpdateUserRequest();
            inValue.Body = new ServiceLoginGTH.UpdateUserRequestBody();
            inValue.Body.item = item;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).UpdateUserAsync(inValue);
        }
        
        public System.Threading.Tasks.Task ActivateUserAsync(int userId)
        {
            return base.Channel.ActivateUserAsync(userId);
        }
        
        public System.Threading.Tasks.Task UnactivateUserAsync(int userId)
        {
            return base.Channel.UnactivateUserAsync(userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserADResponse> ServiceLoginGTH.AuthenticationSoap.AutenticateUserADAsync(ServiceLoginGTH.AutenticateUserADRequest request)
        {
            return base.Channel.AutenticateUserADAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserADResponse> AutenticateUserADAsync(string userName, string password, string domain)
        {
            ServiceLoginGTH.AutenticateUserADRequest inValue = new ServiceLoginGTH.AutenticateUserADRequest();
            inValue.Body = new ServiceLoginGTH.AutenticateUserADRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.domain = domain;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).AutenticateUserADAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.GetDomainsResponse> ServiceLoginGTH.AuthenticationSoap.GetDomainsAsync(ServiceLoginGTH.GetDomainsRequest request)
        {
            return base.Channel.GetDomainsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.GetDomainsResponse> GetDomainsAsync()
        {
            ServiceLoginGTH.GetDomainsRequest inValue = new ServiceLoginGTH.GetDomainsRequest();
            inValue.Body = new ServiceLoginGTH.GetDomainsRequestBody();
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).GetDomainsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserDBResponse> ServiceLoginGTH.AuthenticationSoap.AutenticateUserDBAsync(ServiceLoginGTH.AutenticateUserDBRequest request)
        {
            return base.Channel.AutenticateUserDBAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserDBResponse> AutenticateUserDBAsync(string userName, string password)
        {
            ServiceLoginGTH.AutenticateUserDBRequest inValue = new ServiceLoginGTH.AutenticateUserDBRequest();
            inValue.Body = new ServiceLoginGTH.AutenticateUserDBRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).AutenticateUserDBAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserDBEncripResponse> ServiceLoginGTH.AuthenticationSoap.AutenticateUserDBEncripAsync(ServiceLoginGTH.AutenticateUserDBEncripRequest request)
        {
            return base.Channel.AutenticateUserDBEncripAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserDBEncripResponse> AutenticateUserDBEncripAsync(string userName, string password)
        {
            ServiceLoginGTH.AutenticateUserDBEncripRequest inValue = new ServiceLoginGTH.AutenticateUserDBEncripRequest();
            inValue.Body = new ServiceLoginGTH.AutenticateUserDBEncripRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).AutenticateUserDBEncripAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.ListServersResponse> ServiceLoginGTH.AuthenticationSoap.ListServersAsync(ServiceLoginGTH.ListServersRequest request)
        {
            return base.Channel.ListServersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.ListServersResponse> ListServersAsync()
        {
            ServiceLoginGTH.ListServersRequest inValue = new ServiceLoginGTH.ListServersRequest();
            inValue.Body = new ServiceLoginGTH.ListServersRequestBody();
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).ListServersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserResponse> ServiceLoginGTH.AuthenticationSoap.AutenticateUserAsync(ServiceLoginGTH.AutenticateUserRequest request)
        {
            return base.Channel.AutenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.AutenticateUserResponse> AutenticateUserAsync(int serverId, string userName, string password)
        {
            ServiceLoginGTH.AutenticateUserRequest inValue = new ServiceLoginGTH.AutenticateUserRequest();
            inValue.Body = new ServiceLoginGTH.AutenticateUserRequestBody();
            inValue.Body.serverId = serverId;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).AutenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceLoginGTH.RememberPasswordResponse> ServiceLoginGTH.AuthenticationSoap.RememberPasswordAsync(ServiceLoginGTH.RememberPasswordRequest request)
        {
            return base.Channel.RememberPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceLoginGTH.RememberPasswordResponse> RememberPasswordAsync(string userName)
        {
            ServiceLoginGTH.RememberPasswordRequest inValue = new ServiceLoginGTH.RememberPasswordRequest();
            inValue.Body = new ServiceLoginGTH.RememberPasswordRequestBody();
            inValue.Body.userName = userName;
            return ((ServiceLoginGTH.AuthenticationSoap)(this)).RememberPasswordAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://portaldeservicios.dos.com.ec/CMDBWS/Authentication.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://portaldeservicios.dos.com.ec/CMDBWS/Authentication.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            AuthenticationSoap,
            
            AuthenticationSoap12,
        }
    }
}
